[package]
name = "alcor_base_cc"
version = "0.1.0"
edition = "2021"

[dependencies]
axum = "0.8.1"
diesel = { version = "2.2.8", features = ["sqlite"] }
lazy_static = "1.5.0"
serde = "1.0.218"
tera = "1.20.0"
tokio = { version = "1.43.0", features = ["full"] }
